
package introsde.adapter.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdapterService", targetNamespace = "http://ws.adapter.introsde/", wsdlLocation = "http://192.168.1.5:6903/adapter?wsdl")
public class AdapterService
    extends Service
{

    private final static URL ADAPTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADAPTERSERVICE_EXCEPTION;
    private final static QName ADAPTERSERVICE_QNAME = new QName("http://ws.adapter.introsde/", "AdapterService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.5:6903/adapter?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADAPTERSERVICE_WSDL_LOCATION = url;
        ADAPTERSERVICE_EXCEPTION = e;
    }

    public AdapterService() {
        super(__getWsdlLocation(), ADAPTERSERVICE_QNAME);
    }

    public AdapterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADAPTERSERVICE_QNAME, features);
    }

    public AdapterService(URL wsdlLocation) {
        super(wsdlLocation, ADAPTERSERVICE_QNAME);
    }

    public AdapterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADAPTERSERVICE_QNAME, features);
    }

    public AdapterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdapterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Interface
     */
    @WebEndpoint(name = "ImplementationPort")
    public Interface getImplementationPort() {
        return super.getPort(new QName("http://ws.adapter.introsde/", "ImplementationPort"), Interface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Interface
     */
    @WebEndpoint(name = "ImplementationPort")
    public Interface getImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.adapter.introsde/", "ImplementationPort"), Interface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADAPTERSERVICE_EXCEPTION!= null) {
            throw ADAPTERSERVICE_EXCEPTION;
        }
        return ADAPTERSERVICE_WSDL_LOCATION;
    }

}
