
package introsde.adapter.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Interface", targetNamespace = "http://ws.adapter.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Interface {


    /**
     * 
     * @return
     *     returns introsde.adapter.ws.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.CreatePersonResponse")
    @Action(input = "http://ws.adapter.introsde/Interface/createPersonRequest", output = "http://ws.adapter.introsde/Interface/createPersonResponse")
    public Person createPerson();

    /**
     * 
     * @param personId
     * @return
     *     returns introsde.adapter.ws.Person
     */
    @WebMethod(operationName = "getAuth_info")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuth_info", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetAuthInfo")
    @ResponseWrapper(localName = "getAuth_infoResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetAuthInfoResponse")
    @Action(input = "http://ws.adapter.introsde/Interface/getAuth_infoRequest", output = "http://ws.adapter.introsde/Interface/getAuth_infoResponse")
    public Person getAuthInfo(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param weightGoal
     * @param weight
     * @param user
     * @param height
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setInfo", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.SetInfo")
    @ResponseWrapper(localName = "setInfoResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.SetInfoResponse")
    @Action(input = "http://ws.adapter.introsde/Interface/setInfoRequest", output = "http://ws.adapter.introsde/Interface/setInfoResponse")
    public boolean setInfo(
        @WebParam(name = "user", targetNamespace = "")
        Person user,
        @WebParam(name = "weight", targetNamespace = "")
        double weight,
        @WebParam(name = "height", targetNamespace = "")
        double height,
        @WebParam(name = "weight_goal", targetNamespace = "")
        double weightGoal);

    /**
     * 
     * @param weight
     * @param user
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "weightUpdate", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.WeightUpdate")
    @ResponseWrapper(localName = "weightUpdateResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.WeightUpdateResponse")
    @Action(input = "http://ws.adapter.introsde/Interface/weightUpdateRequest", output = "http://ws.adapter.introsde/Interface/weightUpdateResponse")
    public boolean weightUpdate(
        @WebParam(name = "user", targetNamespace = "")
        Person user,
        @WebParam(name = "weight", targetNamespace = "")
        double weight);

    /**
     * 
     * @param foodId
     * @return
     *     returns introsde.adapter.ws.Food
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFood", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetFood")
    @ResponseWrapper(localName = "getFoodResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetFoodResponse")
    @Action(input = "http://ws.adapter.introsde/Interface/getFoodRequest", output = "http://ws.adapter.introsde/Interface/getFoodResponse")
    public Food getFood(
        @WebParam(name = "foodId", targetNamespace = "")
        int foodId);

    /**
     * 
     * @param text
     * @return
     *     returns java.util.List<introsde.adapter.ws.Food>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchFood", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.SearchFood")
    @ResponseWrapper(localName = "searchFoodResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.SearchFoodResponse")
    @Action(input = "http://ws.adapter.introsde/Interface/searchFoodRequest", output = "http://ws.adapter.introsde/Interface/searchFoodResponse")
    public List<Food> searchFood(
        @WebParam(name = "text", targetNamespace = "")
        String text);

    /**
     * 
     * @param recipeId
     * @return
     *     returns introsde.adapter.ws.Recipe
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecipe", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetRecipe")
    @ResponseWrapper(localName = "getRecipeResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetRecipeResponse")
    @Action(input = "http://ws.adapter.introsde/Interface/getRecipeRequest", output = "http://ws.adapter.introsde/Interface/getRecipeResponse")
    public Recipe getRecipe(
        @WebParam(name = "recipeId", targetNamespace = "")
        int recipeId);

    /**
     * 
     * @param text
     * @return
     *     returns java.util.List<introsde.adapter.ws.Recipe>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchRecipes", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.SearchRecipes")
    @ResponseWrapper(localName = "searchRecipesResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.SearchRecipesResponse")
    @Action(input = "http://ws.adapter.introsde/Interface/searchRecipesRequest", output = "http://ws.adapter.introsde/Interface/searchRecipesResponse")
    public List<Recipe> searchRecipes(
        @WebParam(name = "text", targetNamespace = "")
        String text);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.adapter.ws.Exercise>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getExercises", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetExercises")
    @ResponseWrapper(localName = "getExercisesResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetExercisesResponse")
    @Action(input = "http://ws.adapter.introsde/Interface/getExercisesRequest", output = "http://ws.adapter.introsde/Interface/getExercisesResponse")
    public List<Exercise> getExercises();

    /**
     * 
     * @param date
     * @param user
     * @return
     *     returns java.util.List<introsde.adapter.ws.Exercise>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getExerciseEntry", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetExerciseEntry")
    @ResponseWrapper(localName = "getExerciseEntryResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetExerciseEntryResponse")
    @Action(input = "http://ws.adapter.introsde/Interface/getExerciseEntryRequest", output = "http://ws.adapter.introsde/Interface/getExerciseEntryResponse")
    public List<Exercise> getExerciseEntry(
        @WebParam(name = "user", targetNamespace = "")
        Person user,
        @WebParam(name = "date", targetNamespace = "")
        int date);

    /**
     * 
     * @param idExercise
     * @param minutes
     * @param changeSleeping
     * @param user
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editExerciseEntry", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.EditExerciseEntry")
    @ResponseWrapper(localName = "editExerciseEntryResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.EditExerciseEntryResponse")
    @Action(input = "http://ws.adapter.introsde/Interface/editExerciseEntryRequest", output = "http://ws.adapter.introsde/Interface/editExerciseEntryResponse")
    public boolean editExerciseEntry(
        @WebParam(name = "user", targetNamespace = "")
        Person user,
        @WebParam(name = "id_exercise", targetNamespace = "")
        int idExercise,
        @WebParam(name = "minutes", targetNamespace = "")
        int minutes,
        @WebParam(name = "change_sleeping", targetNamespace = "")
        boolean changeSleeping);

    /**
     * 
     * @param days
     * @param user
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveTemplate", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.SaveTemplate")
    @ResponseWrapper(localName = "saveTemplateResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.SaveTemplateResponse")
    @Action(input = "http://ws.adapter.introsde/Interface/saveTemplateRequest", output = "http://ws.adapter.introsde/Interface/saveTemplateResponse")
    public boolean saveTemplate(
        @WebParam(name = "user", targetNamespace = "")
        Person user,
        @WebParam(name = "days", targetNamespace = "")
        int days);

    /**
     * 
     * @param user
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "commitDay", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.CommitDay")
    @ResponseWrapper(localName = "commitDayResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.CommitDayResponse")
    @Action(input = "http://ws.adapter.introsde/Interface/commitDayRequest", output = "http://ws.adapter.introsde/Interface/commitDayResponse")
    public boolean commitDay(
        @WebParam(name = "user", targetNamespace = "")
        Person user);

}
